### ISSUE TITLE
cannot run the quick start example

### ISSUE THREAD

**Issue by Zhen-Peng-Wu** [PKU-DAIR/SGL#5]
**Describe the bug**

**code:**
from sgl.dataset import Planetoid
from sgl.models.homo import SGC
from sgl.tasks import NodeClassification

dataset = Planetoid("pubmed", "./", "official")
model = SGC(prop_steps=3, feat_dim=dataset.num_features, num_classes=dataset.num_classes)

device = "cuda:0"
test_acc = NodeClassification(dataset, model, lr=0.1, weight_decay=5e-5, epochs=200, device=device).test_acc

**bug:**
Traceback (most recent call last):
  File "quick_start.py", line 9, in <module>
    test_acc = NodeClassification(dataset, model, lr=0.1, weight_decay=5e-5, epochs=200, device=device).test_acc
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/sgl/tasks/node_classification.py", line 39, in __init__
    self.__test_acc = self._execute()
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/sgl/tasks/node_classification.py", line 49, in _execute
    self.__model.preprocess(self.__dataset.adj, self.__dataset.x)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/sgl/models/base_model.py", line 25, in preprocess
    self._processed_feat_list = self._pre_graph_op.propagate(
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/sgl/operators/base_op.py", line 32, in propagate
    feat_temp = csr_sparse_dense_matmul(self._adj, prop_feat_list[-1])
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/sgl/operators/utils.py", line 10, in csr_sparse_dense_matmul
    ctl_lib = ctl.load_library("./csrc/libmatmul.so", "./operators/")
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/numpy/ctypeslib.py", line 163, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

**Environment**
- PyG version:2.0.4
- PyTorch versn:1.11.0
- OS:ubuntu18.04
- Python version:3.8.5
- CUDA/cuDNN version:CUDA 11.4
- How we installed PyTorch and PyG (conda, pip, source):conda
- Any other relevant information (e.g., version of torch-scatter):
- pytorch-scatter:2.0.9
- pytorch-sparse:0.6.13
- pytorch-spline-conv:1.2.1
- pytorch-cluster:1.6.0
- torch-geometric:2.0.4
- torchaudio: 0.11.0
- torchvision:0.12.0
- numpy:1.22.3
- scipy:1.8.0

**Question**
I don't know why such a mistake happened. Please help me.

**Comment by shengzeang** [comment]
Sorry for the bother. We have updated the package to the PyPI. Please update the package via pip. It should be able to run successfully now without reporting errors.

**Comment by Zhen-Peng-Wu** [comment]
I solved this problem by copying the contents of the SGL package to the project path, but thank you for your answer.
